# Generated by Django 4.1.1 on 2022-11-02 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('fto', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(default='None', on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.empassignment')),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
