# Generated by Django 4.1.1 on 2023-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_timeoffrequest_employee_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(default='2023-04-25'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('admin', 'admin'), ('Deputy', 'Deputy'), ('Investigator', 'Investigator'), ('Sergeant', 'Sergeant'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Deputy Chief', 'Deputy Chief'), ('Sheriff', 'Sheriff')], max_length=20),
        ),
    ]
