# Generated by Django 4.1.1 on 2023-04-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge_number',
            field=models.IntegerField(default=500, unique=True),
        ),
    ]
