# Generated by Django 4.1.1 on 2023-04-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_badge_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='title',
            field=models.CharField(choices=[('admin', 'admin'), ('Deputy', 'Deputy'), ('Investigator', 'Investigator'), ('Sergeant', 'Sergeant'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Deputy Chief', 'Deputy Chief'), ('Sheriff', 'Sheriff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge_number',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('admin', 'admin'), ('Deputy', 'Deputy'), ('Investigator', 'Investigator'), ('Sergeant', 'Sergeant'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Deputy Chief', 'Deputy Chief'), ('Sheriff', 'Sheriff')], max_length=20),
        ),
    ]
