# Generated by Django 4.1.1 on 2022-11-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_employees_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='assignment',
        ),
    ]
