# Generated by Django 4.1.1 on 2023-04-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_employees_title_alter_user_badge_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
