# Generated by Django 4.1.1 on 2022-11-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_employees_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.IntegerField(default=501, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='title',
            field=models.CharField(choices=[('Deputy', 'Deputy'), ('Investigator', 'Investigator'), ('Sergeant', 'Sergeant'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Deputy Chief', 'Deputy Chief'), ('Sheriff', 'Sheriff')], max_length=20),
        ),
    ]
