# Generated by Django 4.1.1 on 2023-04-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ivesdale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('employee', models.CharField(choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30)),
                ('start_miles', models.IntegerField()),
                ('end_miles', models.IntegerField()),
                ('total_miles', models.IntegerField()),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
                ('total_time', models.IntegerField()),
                ('weather', models.CharField(choices=[('Clear', 'Clear'), ('Rain', 'Rain'), ('Snow', 'Snow')], max_length=10)),
                ('patrolCar_timeSpent', models.IntegerField()),
                ('patrolCar_activityLog', models.CharField(max_length=200)),
                ('patrolFoot_timeSpent', models.IntegerField()),
                ('patrolFoot_activityLog', models.CharField(max_length=200)),
                ('reportWriting_timeSpent', models.IntegerField()),
                ('reportWriting_activityLog', models.CharField(max_length=200)),
                ('court_timeSpent', models.IntegerField()),
                ('court_activityLog', models.CharField(max_length=200)),
                ('trafficDetail_timeSpent', models.IntegerField()),
                ('trafficDetail_activityLog', models.CharField(max_length=200)),
                ('specialDetail_timeSpent', models.IntegerField()),
                ('specialDetail_activityLog', models.CharField(max_length=200)),
                ('investigateAccident_timeSpent', models.IntegerField()),
                ('investigateAccident_activityLog', models.CharField(max_length=200)),
                ('investigateCriminal_timeSpent', models.IntegerField()),
                ('investigateCriminal_activityLog', models.CharField(max_length=200)),
                ('investigateOther_timeSpent', models.IntegerField()),
                ('investigateOther_activityLog', models.CharField(max_length=200)),
                ('total_timeSpent', models.IntegerField()),
                ('arrestTraffic_count', models.IntegerField()),
                ('arrestTraffic_activityLog', models.CharField(default=0, max_length=10)),
                ('arrestCriminal_count', models.IntegerField()),
                ('arrestCriminal_activityLog', models.CharField(default=0, max_length=10)),
                ('writtenWarnings_count', models.IntegerField()),
                ('writtenWarnings_activityLog', models.CharField(default=0, max_length=10)),
                ('complaintsAnswered_count', models.IntegerField()),
                ('complaintsAnswered_activityLog', models.CharField(default=0, max_length=10)),
                ('accidentsInvestigated_count', models.IntegerField()),
                ('accidentsInvestigated_activityLog', models.CharField(default=0, max_length=10)),
                ('vehiclesInvolved_count', models.IntegerField()),
                ('injuries_count', models.IntegerField()),
                ('fatalities_count', models.IntegerField()),
                ('papersServed_count', models.IntegerField()),
                ('papersServed_activityLog', models.CharField(default=0, max_length=10)),
                ('submissionDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
