# Generated by Django 4.1.1 on 2023-04-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsheet',
            name='employee',
            field=models.CharField(choices=[('Deputy Gabra #503', '#503'), ('Deputy Hubbard #538', '#538')], max_length=30),
        ),
    ]
