# Generated by Django 4.1.1 on 2023-04-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ivesdale',
            name='total_timeSpent',
        ),
        migrations.AddField(
            model_name='ivesdale',
            name='carNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ivesdale',
            name='fatalities_activityLog',
            field=models.TextField(default=2009),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ivesdale',
            name='injuries_activityLog',
            field=models.TextField(default=2009),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ivesdale',
            name='vehiclesInvolved_activityLog',
            field=models.TextField(default=2009),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ivesdale',
            name='village',
            field=models.CharField(default=2009, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='accidentsInvestigated_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='arrestCriminal_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='arrestTraffic_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='complaintsAnswered_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='court_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='employee',
            field=models.CharField(choices=[('Deputy Gabra #503', 'Deputy Gabra #503'), ('Deputy Plotner #539', 'Deputy Plotner #539'), ('Sergeant Herrig #541', 'Sergeant Herrig #541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='investigateAccident_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='investigateCriminal_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='investigateOther_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='papersServed_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='patrolCar_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='patrolFoot_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='patrolFoot_timeSpent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='reportWriting_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='specialDetail_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='trafficDetail_activityLog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ivesdale',
            name='writtenWarnings_activityLog',
            field=models.TextField(),
        ),
    ]
