from django.db import models
from django.conf import settings
# Create your models here.

class ContractSheet(models.Model):
    village = models.CharField(max_length=15)
    date = models.DateField(auto_now_add=False, auto_now=False, blank=False)
    employee = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    carNumber = models.IntegerField()
    start_miles = models.IntegerField()
    end_miles = models.IntegerField()
    total_miles = models.IntegerField()
    start_time = models.TimeField(default='00:00:00')
    end_time = models.TimeField(default='00:00:00')
    total_time = models.IntegerField()
    weather = models.CharField(max_length=10, choices=[(
        'Clear', 'Clear'), ('Rain', 'Rain'), ('Snow', 'Snow')])
    
    patrolCar_timeSpent = models.IntegerField()
    patrolCar_activityLog = models.TextField(blank=True)
    patrolFoot_timeSpent = models.IntegerField()
    patrolFoot_activityLog = models.TextField(blank=True)
    reportWriting_timeSpent = models.IntegerField()
    reportWriting_activityLog = models.TextField(blank=True)
    court_timeSpent = models.IntegerField()
    court_activityLog = models.TextField(blank=True)
    trafficDetail_timeSpent = models.IntegerField()
    trafficDetail_activityLog = models.TextField(blank=True)
    specialDetail_timeSpent = models.IntegerField()
    specialDetail_activityLog = models.TextField(blank=True)
    investigateAccident_timeSpent = models.IntegerField()
    investigateAccident_activityLog = models.TextField(blank=True)
    investigateCriminal_timeSpent = models.IntegerField()
    investigateCriminal_activityLog = models.TextField(blank=True)
    investigateOther_timeSpent = models.IntegerField()
    investigateOther_activityLog = models.TextField(blank=True)

    arrestTraffic_count = models.IntegerField()
    arrestTraffic_activityLog = models.TextField(blank=True)
    arrestCriminal_count = models.IntegerField()
    arrestCriminal_activityLog = models.TextField(blank=True)
    writtenWarnings_count = models.IntegerField()
    writtenWarnings_activityLog = models.TextField(blank=True)
    complaintsAnswered_count = models.IntegerField()
    complaintsAnswered_activityLog = models.TextField(blank=True)
    accidentsInvestigated_count = models.IntegerField()
    accidentsInvestigated_activityLog = models.TextField(blank=True)
    vehiclesInvolved_count = models.IntegerField()
    vehiclesInvolved_activityLog = models.TextField(blank=True)
    injuries_count = models.IntegerField()
    injuries_activityLog = models.TextField(blank=True)
    fatalities_count = models.IntegerField()
    fatalities_activityLog = models.TextField(blank=True)
    papersServed_count = models.IntegerField()
    papersServed_activityLog = models.TextField(blank=True)

    submissionDate = models.DateTimeField(auto_now_add=True)
