# Generated by Django 4.1.1 on 2023-04-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilServiceOne',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CivilServiceTwo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='East',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='North',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('beat_assignment', models.CharField(blank=True, choices=[('North (1/2)', 'North (1/2)'), ('West (3/4)', 'West (3/4)'), ('Cover (4/5)', 'Cover (4/5)'), ('East (5/6)', 'East (5/6)'), ('South (7/8)', 'South (7/8)'), ('Savoy (10)', 'South (10)'), ('St. Joseph (11)', 'St. Joseph (11)'), ('Field Training (FTO)', 'Field Training (FTO)'), ('Training', 'Training'), ('Recruit', 'Recruit')], max_length=30)),
                ('employee', models.CharField(blank=True, choices=[], max_length=30)),
                ('start_time', models.TimeField(default='06:00:00')),
                ('end_time', models.TimeField(default='06:00:00')),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SaintJoseph',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SavoyOne',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SavoyThree',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SavoyTwo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftCommanderOne',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftCommanderTwo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='South',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.CharField(default='Deputy TEST', max_length=30)),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('vacation', models.CharField(default=0, max_length=10)),
                ('comp', models.CharField(default=0, max_length=10)),
                ('holiday', models.CharField(default=0, max_length=10)),
                ('sick', models.CharField(default=0, max_length=10)),
                ('personal', models.CharField(default=0, max_length=10)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('reviewed', models.DateTimeField(auto_now=True)),
                ('supervisor', models.CharField(default='Sgt. TEST', max_length=30)),
                ('supervisor_comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='West',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmpAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(choices=[('None', 'None'), ('Gold Days', 'Gold Days'), ('Gold Nights', 'Gold Nights'), ('Brown Days', 'Brown Days'), ('Brown Nights', 'Brown Nights'), ('St. Joseph', 'St. Joseph'), ('Savoy', 'Savoy'), ('Civil Process', 'Civil Process'), ('Investigations', 'Investigations'), ('Command Staff', 'Command Staff')], default='None', max_length=20)),
                ('short_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
            ],
        ),
    ]
