# Generated by Django 4.1.1 on 2022-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(choices=[('None', 'None'), ('Gold Days', 'Gold Days'), ('Gold Nights', 'Gold Nights'), ('Brown Days', 'Brown Days'), ('Brown Nights', 'Brown Nights'), ('St. Joseph', 'St. Joseph'), ('Savoy', 'Savoy'), ('Civil Process', 'Civil Process'), ('Investigations', 'Investigations'), ('Command Staff', 'Command Staff')], default='None', max_length=20)),
                ('short_day', models.CharField(blank=True, max_length=20)),
            ],
        ),
        
    ]
