# Generated by Django 4.1.1 on 2023-04-27 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='supervisor',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='EmpAssignment',
        ),
    ]
