# Generated by Django 4.1.1 on 2022-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='assignment',
            field=models.CharField(default='EMPTY', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(default='EMPTY@co.champaign.il.us', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='fto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='password',
            field=models.CharField(default='EMPTY', max_length=20),
            preserve_default=False,
        ),
    ]
