# Generated by Django 4.1.1 on 2023-03-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_civilserviceone_civilservicetwo_cover_east_north_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='comp_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='holiday_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='personal_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='sick_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='vacation_hours',
            field=models.IntegerField(default=0),
        ),
    ]
