# Generated by Django 4.1.1 on 2022-10-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_employees_admin_employees_assignment_employees_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
