# Generated by Django 4.1.1 on 2023-03-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_civilserviceone_civilservicetwo_cover_east_north_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilserviceone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilserviceone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilservicetwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilservicetwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='other',
            name='employee',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='saintjoseph',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='saintjoseph',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoyone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoyone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoythree',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoythree',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoytwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoytwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy d #501', '501'), ('Deputy s #502', '502')], max_length=30),
        ),
    ]
