# Generated by Django 4.1.1 on 2022-11-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_employees_assignment'),
        ('scheduling', '0002_empassignment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empassignment',
            name='employee',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='home.employees'),
        ),
    ]
