# Generated by Django 4.1.1 on 2023-03-27 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_civilserviceone_civilservicetwo_cover_east_north_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='comp_hours',
            new_name='comp',
        ),
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='holiday_hours',
            new_name='holiday',
        ),
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='personal_hours',
            new_name='personal',
        ),
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='sick_hours',
            new_name='sick',
        ),
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='vacation_hours',
            new_name='vacation',
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='reviewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='supervisor',
            field=models.CharField(default='Sgt. TEST', max_length=30),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='supervisor_comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='civilserviceone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilserviceone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilservicetwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilservicetwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='other',
            name='employee',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='saintjoseph',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='saintjoseph',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoyone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoyone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoythree',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoythree',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoytwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoytwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='employee',
            field=models.CharField(default='Deputy TEST', max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Plotner #539', '539'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
    ]
