# Generated by Django 4.1.1 on 2023-04-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_timeoffrequest_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='supervisor',
            field=models.CharField(max_length=30),
        ),
    ]
