# Generated by Django 4.1.1 on 2023-03-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_timeoffrequest_comp_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='comp_hours',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='holiday_hours',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='personal_hours',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='sick_hours',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='vacation_hours',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
