# Generated by Django 4.1.1 on 2023-03-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_civilserviceone_first_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
