# Generated by Django 4.1.1 on 2022-11-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_employees_assignment'),
        ('scheduling', '0003_alter_empassignment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees'),
        ),
        migrations.AlterField(
            model_name='empassignment',
            name='short_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wendesday', 'Wendesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
