# Generated by Django 4.1.1 on 2022-10-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('scheduling', '0003_delete_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrol_Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=20)),
                ('short_day', models.CharField(blank=True, max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employees')),
            ],
        ),
    ]
