# Generated by Django 4.1.1 on 2023-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_other_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
