# Generated by Django 4.1.1 on 2022-11-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_empassignment_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golddays',
            name='commandOne_first_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='commandOne_second_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='commandOne_third_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='commandTwo_first_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='commandTwo_second_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='commandTwo_third_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='cover_first_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='cover_second_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='cover_third_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='east_first_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='east_second_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='east_third_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='north_first_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='north_second_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='north_third_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='south_first_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='south_second_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='south_third_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='west_first_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='west_second_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='golddays',
            name='west_third_four',
            field=models.CharField(choices=[], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='empassignment',
            name='short_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
