# Generated by Django 4.1.1 on 2022-11-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_golddays_commandone_first_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_first_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_second_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_third_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_first_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_second_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_third_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_first_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_second_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_third_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_first_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_second_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_third_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_first_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_second_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_third_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_first_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_second_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_third_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_first_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_second_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_third_four',
            field=models.CharField(choices=[('None', 'None'), ("('Deputy', 'Test123', 501)", "('Deputy', 'Test123', 501)"), ("('Deputy', 'Stevens', 502)", "('Deputy', 'Stevens', 502)")], default='None', max_length=30),
        ),
    ]
