# Generated by Django 4.1.1 on 2023-01-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_golddays_commandone_first_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503'), ('Deputy Livingston #508', '508'), ('Deputy Hubbard #538', '538'), ('Sergeant Herrig #541', '541')], default='None', max_length=30),
        ),
    ]
