# Generated by Django 4.1.1 on 2023-03-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_remove_cover_foruth_four_remove_east_foruth_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilserviceone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilserviceone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilservicetwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='civilservicetwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cover',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='east',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='north',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='other',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='other',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='saintjoseph',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='saintjoseph',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoyone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoyone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoythree',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoythree',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoytwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='savoytwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommandertwo',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='south',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
        migrations.AlterField(
            model_name='west',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Deputy Gabra #503', '503')], max_length=30),
        ),
    ]
