# Generated by Django 4.1.1 on 2023-03-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_alter_civilserviceone_first_four_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CivilServiceOne',
        ),
        migrations.DeleteModel(
            name='CivilServiceTwo',
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
        migrations.DeleteModel(
            name='East',
        ),
        migrations.DeleteModel(
            name='North',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='SaintJoseph',
        ),
        migrations.DeleteModel(
            name='SavoyOne',
        ),
        migrations.DeleteModel(
            name='SavoyThree',
        ),
        migrations.DeleteModel(
            name='SavoyTwo',
        ),
        migrations.DeleteModel(
            name='ShiftCommanderTwo',
        ),
        migrations.DeleteModel(
            name='South',
        ),
        migrations.DeleteModel(
            name='West',
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_first_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_second_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_third_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_first_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_second_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_third_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_first_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_second_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_third_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_first_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_second_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_third_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_first_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_second_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_third_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_first_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_second_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_third_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_first_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_second_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_third_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='first_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='second_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='third_four',
            field=models.CharField(blank=True, choices=[('Lieutenant da #501', '501')], max_length=30),
        ),
    ]
