# Generated by Django 4.1.1 on 2023-03-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_delete_civilserviceone_delete_civilservicetwo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilServiceOne',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CivilServiceTwo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='East',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='North',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SaintJoseph',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SavoyOne',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SavoyThree',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SavoyTwo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftCommanderTwo',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='South',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='West',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('first_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('second_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('third_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fourth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('fifth_four', models.CharField(blank=True, choices=[], max_length=30)),
                ('sixth_four', models.CharField(blank=True, choices=[], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_first_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_second_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandOne_third_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_first_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_second_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='commandTwo_third_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_first_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_second_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='cover_third_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_first_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_second_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='east_third_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_first_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_second_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='north_third_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_first_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_second_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='south_third_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_first_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_second_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='golddays',
            name='west_third_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fifth_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='first_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='fourth_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='second_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='sixth_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftcommanderone',
            name='third_four',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
    ]
